NANOSECONDS = 1
MICROSECONDS = 1000 * NANOSECONDS
MILLISECONDS = 1000 * MICROSECONDS
SECONDS = 1000 * MILLISECONDS

MINE_RATE = 4 * SECONDS 

STARTING_BALANCE = 1000

MININIG_REWARD = 50
MININIG_REWARD_INPUT = {'address' : '*--official-mining-reward--*'}