class TransactionPool:
    def __init__(self):
        self.transaction_map = {}

    def set_transaction(self, transaction):
        """Set a transaction in the transaction pool."""
        self.transaction_map[transaction.id] = transaction

    def existing_transaction(self, adress):
        """Find a transact generated by the adress in the 
        transaction pool"""
        for transaction in self.transaction_map.values():
            if transaction.input['address'] == adress:
                return transaction
